### ISSUE TITLE
Проверка дз

### ISSUE THREAD

**Issue by AinurAbdullaeva** [AinurAbdullaeva/Homework-WPF#1]
Сергей Иванович, проверьте пожалуйста мои задания до 7 лекции включительно!!!
**Дз лекция 1:** 
 Абдуллаева Айнур 
 Сертификат о прохождениии курса: https://www.sololearn.com/certificates/CC-ZYHZQTR3

 

**Дз лекция 2:** 
Задача 1.2 добавлена на гит хаб 
Сертификат о прохождении курса : https://www.sololearn.com/certificates/CC-AFENPTHH 

 
**Дз лекция 3,4:** 
В задаче 1.2 запись и чтение в файл, класс для бросания тела. Входило в день коммита задачи 1.2 

**Дз лекция  5:** 
Добавлено под названием event

**Comment by justjune** [comment]
Айнур, см. Успеваемость.
