### ISSUE TITLE
Проверка дз

### ISSUE THREAD

**Issue by AinurAbdullaeva** [AinurAbdullaeva/Homework-WPF#2]
1.  Выложен код по методу Эйлера (Eyler's Method),  код с кнопками, запуском события и отображением события о столкновении в главном окне (WpF2)
Сергей Иванович, почему у меня за 1-3 лекцию ничего  не проставлено? в предыдущем сообщении прикреплены ссылки на сертификаты о прохождении курсов
Почему за практику 3(чтение и запись в файл стоит только 50 баллов)?

**Comment by justjune** [comment]
Айнур, проставил. См. Успеваемость. за практику 3 100 баллов стоит.
